`Numpy` (NUMerical PYthon) is a package in python used to transform numeric data 
-
- The basic data structure(collection) in numpy is the array
 
 - 1-D Arrays are called `vectors`,2-D Array are called `Matrices`  and more than 2-D arrays are called `nd arrays`.
    

 Creating arrays 
 -
 1.From the existing collections
 -
 

In [2]:
li =[1,2,3,4,5]
print(li)
print(type(li))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
import numpy as np
arr = np.array(li)
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


 - We can create arrays from existing collections using the method `np.array()` and the datatype of the resultamt collection is ```  `numpy.ndarray` 

In [19]:
li1 = [1,2],[3,4]
li2 = [4,5],[6,7]
arr = np.array(li1+li2)
print(li)
print(arr)

([1, 2], [3, 4])
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


### FROM METHODS ( crreating of array)
 `arange`
 - The method `arange` is used to crate an array which has sequence of numbers.


In [22]:
Arr = np.arange(5)
Arr

array([0, 1, 2, 3, 4])

In [38]:
arr1 = np.arange(10,21,2)
arr2=np.arange(20,32,2)
print(arr1,arr2)
add = np.add(arr1,arr2)
print(add)

[10 12 14 16 18 20] [20 22 24 26 28 30]
[30 34 38 42 46 50]


In [37]:
arr1 = np.arange(10,21,2)
arr1

array([10, 12, 14, 16, 18, 20])

## Creating an array which has only `ONES` in it 

In [45]:
# creating a 1-d array with four elements 
arr = np.ones(4,dtype=int)
arr

array([1, 1, 1, 1])

In [62]:
# 
arr = np.ones(shape=(2,4),dtype='int64')  # int64 or int = 32 by default
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

*` ZEROS`*
- 
- Creating an array which has `0's`.

In [56]:
# create a 1-D array with 6 elements in it 
arr = np.zeros(6,dtype=int)
arr

array([0, 0, 0, 0, 0, 0])

In [63]:
# create a 2-D array of shape(3,4)
arr = np.zeros(shape=(3,4),dtype='int64')
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

 *`EYE`*
 -
  - This method is used to generate the identity matrix.

In [64]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
arr =np.eye(3,dtype='int64')
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

*`linspace`*
-
- This method is used to return an array of equal intervals in a given range where both the limits are inclusive .
- return an array with equal distance  interval in a given range where the both limit are inclusive.

In [72]:
arr = np.linspace(1 ,5,10) #( low -limt,high limit,size)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [77]:
arr = np.linspace(1,5)
arr

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

**`random`**
-
- The `random` sub-module in python is used to generate different random numbers.
- `rand`
- The `rand()` method is used to create random numbers in the range [0,1)(uniform distribution).

In [91]:
arr = np.random.rand(5)
arr

array([0.33076811, 0.54134012, 0.48617119, 0.3662365 , 0.88156249])

In [92]:
arr = np.random.rand(4,5)
arr # matrix

array([[0.26527881, 0.23322955, 0.99199969, 0.28407942, 0.54797497],
       [0.90534444, 0.93002163, 0.99833916, 0.39550308, 0.31598667],
       [0.24539943, 0.20073217, 0.08564537, 0.24094335, 0.94673611],
       [0.58096872, 0.6223983 , 0.91538475, 0.28309696, 0.54725747]])

*`randn`*
- 
- The `randn()` method is used to create random numbers from the standard normal distribution(-3,3).

In [109]:
arr = np.random.randn(6)
arr

array([-1.28611651,  0.49659911, -0.09358276, -0.76976691,  1.06358504,
        0.77510964])

In [104]:
arr = np.random.randn(2,5)
arr

array([[ 0.78376127, -0.52254559, -1.44395298, -0.10104953,  0.6803989 ],
       [-0.69694396,  0.36971482, -1.33969651,  0.74930573,  0.43166891]])

*`randint`*
-
- THE method `randint()` is used to generate random integers in a given range.

In [132]:
np.random.seed(100)
arr = np.random.randint(1,100,(10,10),dtype='int64')
arr

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28],
       [57, 31, 49, 48, 40, 39, 45, 19, 65, 57],
       [35, 54, 75, 18, 73, 14, 31, 18, 54, 69],
       [51, 92, 92, 84, 54, 79,  1, 14, 58, 77],
       [ 4, 71,  4, 85, 80, 11, 88, 61,  4, 49],
       [53, 44, 37,  6, 72, 39, 87, 95, 99, 43]])

- The `seed` method is used to fix the random values so that whoever uses the same seed method gets the same random numbers.

### `INDEXING ARRAYS`

In [141]:
user1 = int(input('Enter the number'))
user2 = int(input('Enter the number'))
rand1=int(input('Enter the number'))
rand2=int(input('Enter the number'))
arr = np.random.randint(rand1,rand2,(user1,user2),dtype='int64')
arr

Enter the number 5
Enter the number 5
Enter the number 1
Enter the number 100


array([[ 3, 88, 77, 40, 37],
       [36, 27, 20,  5, 40],
       [88, 75, 80, 93, 53],
       [45, 14, 34, 16, 18],
       [89, 24, 60,  9, 41]])

- Indexing a rxc array in numpy is done like arr[r,c]

In [147]:
arr[2] # row indexing

np.int64(80)

In [149]:
arr[3:5] # row indexing

array([[45, 14, 34, 16, 18],
       [89, 24, 60,  9, 41]])

In [151]:
arr[: :2]# row indexing

array([[ 3, 88, 77, 40, 37],
       [88, 75, 80, 93, 53],
       [89, 24, 60,  9, 41]])

In [154]:
arr[:,2] # column indexing 

array([77, 20, 80, 34, 60])

In [155]:
arr[:,-2]   # column indexing 

array([40,  5, 93, 16,  9])

In [157]:
arr[:,0:3 ] # column indexing 

array([[ 3, 88, 77],
       [36, 27, 20],
       [88, 75, 80],
       [45, 14, 34],
       [89, 24, 60]])

In [163]:
arr[:,[2,3,4]]

array([[77, 40, 37],
       [20,  5, 40],
       [80, 93, 53],
       [34, 16, 18],
       [60,  9, 41]])

In [164]:
arr[2:3,3:4]

array([[93]])

In [165]:
arr

array([[ 3, 88, 77, 40, 37],
       [36, 27, 20,  5, 40],
       [88, 75, 80, 93, 53],
       [45, 14, 34, 16, 18],
       [89, 24, 60,  9, 41]])

In [167]:
# to know the shape of an array
print('The shape of the array is ',arr.shape)

The shape of the array is  (5, 5)


In [168]:
# to know the datatype in array 
arr.dtype

dtype('int64')

In [169]:
# to extract the minimum value in the entire array
arr.min()

np.int64(3)

In [170]:
# to extract the minimum value in the each row of  array
arr.min(axis=1)

array([ 3,  5, 53, 14,  9])

In [171]:
# to extract the minimum value in the each ** COLUMN** of  array
arr.min(axis=0)

array([ 3, 14, 20,  5, 18])

In [172]:
# to extract the maximum value in the entire array
arr.max()

np.int64(93)